import {
  Container,
  Grid,
  List,
  ListItem,
  ListItemButton,
  Typography,
} from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ReactNode } from "react";

type Props = { title: string; children: ReactNode };

export function Layout({ children, title }: Props) {
  const { pathname } = useRouter();

  return (
    <Container>
      <Head>
        <title>{title}</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant="h4" sx={{ mt: 2, mb: 1 }}>
        {title}
      </Typography>

      <Grid container spacing={2}>
        <Grid item xs={12} sm={2}>
          <List>
            <ListItem disablePadding>
              <Link href="/">
                <ListItemButton component="a" selected={pathname === "/"}>
                  Offers
                </ListItemButton>
              </Link>
            </ListItem>

            <ListItem disablePadding>
              <Link href="/contacts">
                <ListItemButton
                  component="a"
                  selected={pathname === "/contacts"}
                >
                  Contacts
                </ListItemButton>
              </Link>
            </ListItem>

            <ListItem disablePadding>
              <Link href="/settings">
                <ListItemButton
                  component="a"
                  selected={pathname === "/settings"}
                >
                  Settings
                </ListItemButton>
              </Link>
            </ListItem>
          </List>
        </Grid>

        <Grid item xs={12} sm={10}>
          {children}
        </Grid>
      </Grid>
    </Container>
  );
}
